title: Cobra RattleSnake
description: Taiwanese-inspired hot sauces for riders, eaters, and heat seekers.
url: "https://durrutia.github.io"
baseurl: "/cobra-rattlesnake"
markdown: kramdown
theme: null
plugins: []
collections:
  products:
    output: true
    permalink: /products/:name/
